//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by GitVersion.
// 
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated> 
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("2.0.0.0")]
[assembly: AssemblyVersion("2.0.0.0")]
[assembly: AssemblyInformationalVersion("2.0.0-beta.1+0.Branch.release/2.0.Sha.cbf984f3c15044943fef6b7e94fe15228a5223f4")]